---
version: "3"

services:
  poller:
    build: .
    environment:
    - POLLER_NATS_URL
    - POLLER_LOG_LEVEL
    command: /bin/git-poller
    ports:
    - "9002:9002"
  queue:
    image: nats
    ports:
    - "4222:4222"
    - "5222:5222"
    - "6222:6222"
