---
summary: Build `git-poller`.

description: |
  The `build` task builds `git-poller` in the current directory.

  This task runs in a Linux container. If working on Mac OS
  make sure to set GOOS appropriately.

image: golang:1.11-stretch

mount: /go/src/github.com/run-ci/git-poller

command: go build -v

arguments:
  GOOS:
    description: Platform to build for.
    default: linux
